import { useState, useEffect } from 'react';
import api from '../../services/api';
import { FiAward } from 'react-icons/fi';

const ALL_SUBJECTS = [
  'Data Structures and Algorithms (DSA)', 
  'Mathematics', 
  'Operating Systems (OS)', 
  'Computer Networks', 
  'Database Management Systems (DBMS)'
];

export default function StudentViewResults() {
  const [selectedSubject, setSelectedSubject] = useState('');
  const [academicRecords, setAcademicRecords] = useState([]);
  const [currentResult, setCurrentResult] = useState(null);

  useEffect(() => {
    fetchAcademics();
  }, []);

  const fetchAcademics = async () => {
    try {
      const res = await api.get('/student/academic');
      setAcademicRecords(res.data?.records || []);
    } catch (e) {
      console.error(e);
    }
  };

  const handleSubjectSelect = (sub) => {
    setSelectedSubject(sub);
    const result = academicRecords.find(r => r.subject === sub);
    setCurrentResult(result || null);
  };

  return (
    <>
      <div className="card full-width">
        <div className="card-header">
          <h3>View My Results</h3>
          <span className="badge blue">Select Subject</span>
        </div>
        <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap', marginTop: 12 }}>
          {ALL_SUBJECTS.map(sub => (
            <button 
              key={sub} 
              className={`btn ${selectedSubject === sub ? 'btn-primary' : 'btn-outline'}`}
              onClick={() => handleSubjectSelect(sub)}
              style={{ flex: 1, minWidth: '120px' }}
            >
              {sub}
            </button>
          ))}
        </div>
      </div>

      {selectedSubject && (
        <div className="card full-width" style={{ marginTop: 20 }}>
          <div className="card-header">
            <h3>Academic Results: {selectedSubject}</h3>
            <span className="badge purple"><FiAward /> Transcript</span>
          </div>
          
          <div style={{ marginTop: 24, display: 'flex', flexDirection: 'column', gap: '20px' }}>
            {currentResult ? (
              <>
                <div style={{ display: 'flex', justifyContent: 'space-around', background: 'var(--bg)', padding: '24px', borderRadius: '16px', border: '1px solid var(--border)', textAlign: 'center' }}>
                  <div>
                    <h4 style={{ color: 'var(--text-muted)' }}>CCA / 10</h4>
                    <p style={{ fontSize: '1.5rem', fontWeight: 700, color: 'var(--text)' }}>{currentResult.cca}</p>
                  </div>
                  <div>
                    <h4 style={{ color: 'var(--text-muted)' }}>LCA / 10</h4>
                    <p style={{ fontSize: '1.5rem', fontWeight: 700, color: 'var(--text)' }}>{currentResult.lca}</p>
                  </div>
                  <div>
                    <h4 style={{ color: 'var(--text-muted)' }}>Project / 30</h4>
                    <p style={{ fontSize: '1.5rem', fontWeight: 700, color: 'var(--text)' }}>{currentResult.project}</p>
                  </div>
                  <div>
                    <h4 style={{ color: 'var(--text-muted)' }}>Midsem / 20</h4>
                    <p style={{ fontSize: '1.5rem', fontWeight: 700, color: 'var(--text)' }}>{currentResult.midsem}</p>
                  </div>
                  <div>
                    <h4 style={{ color: 'var(--text-muted)' }}>Endsem / 30</h4>
                    <p style={{ fontSize: '1.5rem', fontWeight: 700, color: 'var(--text)' }}>{currentResult.endsem}</p>
                  </div>
                </div>

                <div style={{ background: 'linear-gradient(135deg, var(--teal-500), var(--blue-600))', color: 'white', padding: '32px', borderRadius: '16px', textAlign: 'center' }}>
                  <p style={{ fontSize: '1.2rem', marginBottom: 8, opacity: 0.9 }}>Final Percentage Generated By Admin & Teacher</p>
                  <h1 style={{ fontSize: '3rem', margin: 0 }}>{currentResult.total_percentage || 0}%</h1>
                  <p style={{ marginTop: 8, fontWeight: 500, opacity: 0.9 }}>Grade: {currentResult.grade || 'N/A'}</p>
                </div>
              </>
            ) : (
              <div style={{ padding: '32px', textAlign: 'center', background: 'var(--bg)', borderRadius: '16px', border: '1px dashed var(--border)' }}>
                <h4 style={{ color: 'var(--text-muted)' }}>No marks uploaded yet by teacher for {selectedSubject}.</h4>
              </div>
            )}
          </div>
        </div>
      )}
    </>
  );
}
